spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loja_automatica
    username: postgres
    password: 247935
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
