CREATE TABLE IF NOT EXISTS token (
    id BIGSERIAL PRIMARY KEY,
    confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    token VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE CASCADE
);